# Generated by Django 3.2.5 on 2022-02-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=50, unique=True)),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=50)),
            ],
        ),
    ]
