# Generated by Django 3.2.5 on 2022-02-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Requests_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True)),
                ('client_email', models.EmailField(max_length=50, null=True)),
                ('file_name', models.CharField(max_length=50, null=True)),
                ('user_file', models.FileField(null=True, upload_to='request/')),
                ('same', models.BooleanField(default=False)),
                ('temporary_mac', models.BooleanField(default=False)),
                ('different', models.BooleanField(default=False)),
                ('mac', models.CharField(max_length=50, null=True)),
                ('sent_organization', models.BooleanField(default=False)),
                ('client_details', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.client_details')),
            ],
        ),
        migrations.CreateModel(
            name='Change_Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('client_email', models.EmailField(max_length=50, null=True)),
                ('different_mac', models.BooleanField(default=False)),
                ('question_link', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=50, null=True)),
                ('files', models.FileField(null=True, upload_to='request/')),
                ('correct', models.BooleanField(default=False)),
                ('current_mac', models.CharField(max_length=50, null=True)),
                ('sent_user', models.BooleanField(default=False)),
                ('again_link', models.BooleanField(default=False)),
                ('approve', models.BooleanField(default=False)),
                ('director_sent', models.BooleanField(default=False)),
                ('security', models.CharField(max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_details')),
            ],
        ),
    ]
