# Generated by Django 3.2.5 on 2022-02-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=50, unique=True)),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('approve', models.BooleanField(default=False)),
                ('decline', models.BooleanField(default=False)),
                ('question', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('file_name', models.CharField(max_length=50)),
                ('file_format', models.CharField(max_length=20)),
                ('file_weight', models.CharField(max_length=10)),
                ('file_amount', models.IntegerField(null=True)),
                ('fix_amount', models.BooleanField(default=False)),
                ('accept_amount', models.BooleanField(default=False)),
                ('file', models.FileField(null=True, upload_to='file/')),
                ('files', models.BooleanField(default=False)),
                ('send_data', models.BooleanField(default=False)),
                ('encrypt', models.BooleanField(default=False)),
                ('secure_key', models.CharField(max_length=20)),
                ('finish', models.BooleanField(default=False)),
                ('download', models.BooleanField(default=False)),
                ('different', models.BooleanField(default=False)),
                ('company_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company_details')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=50)),
                ('two', models.CharField(max_length=50)),
                ('three', models.CharField(max_length=50)),
                ('four', models.CharField(max_length=50)),
                ('five', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('accept', models.BooleanField(default=False)),
                ('generator_key', models.CharField(max_length=20, null=True)),
                ('download', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.file_details')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=50)),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('accept', models.BooleanField(default=False)),
                ('send_link', models.BooleanField(default=False)),
                ('answer', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.company_details')),
            ],
        ),
    ]
